apiVersion: v1
kind: Pod
metadata:
  name: jx105-playlist-recommender-model-pod
spec:
  restartPolicy: OnFailure
  operation:
    sync:
      syncStrategy:
        apply:
          force: true
  volumes:
    - name: project2-pv-jx105
      persistentVolumeClaim:
        claimName: project2-pvc-jx105
  containers:
    - name: jx105-playlist-recommender-model-container
      image: docker.io/jasonxie5306/spotify-playlist-recommender-model:0.12
      imagePullPolicy: Always
      volumeMounts:
        - name: project2-pv-jx105
          mountPath: /data
      env:
        - name: DATASET_PATH
          value: "https://raw.githubusercontent.com/jason5306/spotify-playlist-recommender-specs/main/playlist-sample-ds2.csv"
        - name: BASE_DIR
          value: "/data"
        - name: SONGS_DIR
          value: "https://raw.githubusercontent.com/jason5306/spotify-playlist-recommender-specs/main/songs.csv"            
